### ISSUE TITLE
White screen of death

### ISSUE THREAD

**Issue by CamsShaft** [whyakari/HttpCanary-Magisk-and-KSU#2]
Hi there, when I try to open the app the screen goes white then closes after a second. Not sure what's up with that. I'm running it on Samsung s22 android 13 which is unrootable of course. I don't have Magick because I thought it was only for rooting a phone and since mine is snapdragon that's out of the question. Thanks for anything!

**Comment by whyakari** [comment]
> Hi there, when I try to open the app the screen goes white then closes after a second. Not sure what's up with that. I'm running it on Samsung s22 android 13 which is unrootable of course. I don't have Magick because I thought it was only for rooting a phone and since mine is snapdragon that's out of the question. Thanks for anything!

This is not related to the module, thankyou
